github actions updates

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -18,7 +18,8 @@ jobs:
     - name: Install Playwright Browsers
       run: npx playwright install --with-deps
     - name: Run Playwright tests
-      run: npx playwright test
+      run: |
+        npx playwright test || exit 1  # This ensures the job fails if tests fail
     - uses: actions/upload-artifact@v4
       if: ${{ !cancelled() }}
       with:
